name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  pengujian-otomatis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - run: |
        pip install -r requirements.txt
        pip install pytest httpx
    - run: python -m pytest

  build-and-push-docker:
    needs: pengujian-otomatis # Hanya jalan jika ujian lolos!
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login ke Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build dan Push ke Docker Hub
      uses: docker/build-push-action@v4
      with:
        push: true
        # Ganti 'username-kamu' dengan username Docker Hub aslimu!
        tags: panjiyudo/devops-python-api:latest